name: event_management_system
description: "It is a event management system."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^4.19.5
  flutter:
    sdk: flutter
  http: ^1.2.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.2
  uuid: ^4.4.0
  table_calendar: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
