// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUVdtl1jTIz7i4NuXHzd1HVZbJ0CKYZs',
    appId: '1:1060963871065:web:8b390feadff172c5f60448',
    messagingSenderId: '1060963871065',
    projectId: 'flutter-project-f90ec',
    authDomain: 'flutter-project-f90ec.firebaseapp.com',
    storageBucket: 'flutter-project-f90ec.appspot.com',
    measurementId: 'G-YEJPPB255L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC16YOrcqC3v4eUCWbxT5rQ6qwHvgYgxQo',
    appId: '1:1060963871065:android:0720e339a4da0673f60448',
    messagingSenderId: '1060963871065',
    projectId: 'flutter-project-f90ec',
    storageBucket: 'flutter-project-f90ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhXn_oCuJeZzrXVKFTWJYGt04C9MoyVDA',
    appId: '1:1060963871065:ios:d709c7f207109ec9f60448',
    messagingSenderId: '1060963871065',
    projectId: 'flutter-project-f90ec',
    storageBucket: 'flutter-project-f90ec.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhXn_oCuJeZzrXVKFTWJYGt04C9MoyVDA',
    appId: '1:1060963871065:ios:d709c7f207109ec9f60448',
    messagingSenderId: '1060963871065',
    projectId: 'flutter-project-f90ec',
    storageBucket: 'flutter-project-f90ec.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdUVdtl1jTIz7i4NuXHzd1HVZbJ0CKYZs',
    appId: '1:1060963871065:web:17d1fb203b83de10f60448',
    messagingSenderId: '1060963871065',
    projectId: 'flutter-project-f90ec',
    authDomain: 'flutter-project-f90ec.firebaseapp.com',
    storageBucket: 'flutter-project-f90ec.appspot.com',
    measurementId: 'G-M6N0EZDS79',
  );
}
